name: Push in main

on:
  push:
    branches: [ main ]

jobs:
  code-checkers:
    uses: firebolt-db/firebolt-cli/.github/workflows/code-check.yml@main
  unit-tests:
    uses: firebolt-db/firebolt-cli/.github/workflows/unit-tests.yml@main
    secrets:
      GIST_PAT: ${{ secrets.GIST_PAT }}
  security-scan:
    needs: [unit-tests]
    uses: firebolt-db/firebolt-cli/.github/workflows/security-scan.yml@main
    secrets:
      FOSSA_TOKEN: ${{ secrets.FOSSA_TOKEN }}
      SONARCLOUD_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}

